### PR TITLE
init

### PR DESCRIPTION
**Pull request by srowhani**

### CODE REVIEW

**Comment by sglanzer-fire** [comment]
Holy files changed batman!  Would you mind redoing this PR with the gitignore on from the start?

Also, I'm more than happy to just review a screenshot on this one, so if you send that to me over slack I'd be happy to 👍

**Comment by srowhani** [comment]
I'll post a screen. 👍

**Comment by EWhite613** [comment]
screenshots:
screen shot 2016-05-27 at 3 45 53 pm
screen shot 2016-05-27 at 3 46 11 pm
screen shot 2016-05-27 at 3 50 00 pm
screen shot 2016-05-27 at 3 50 39 pm

**Comment by sglanzer-fire** [comment]
Just three comments:

Visual Acceptance appears to be missing a space
Let's rename Mocha to Testing and rename Blanket.js to Code Coverage
Label the baseline, current and diff images in failures

**Pull request merged**
